services:
  - type: web
    name: kabianga-lost-and-found
    env: node
    plan: starter
    branch: master
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: SESSION_SECRET
        value: change_this_secret
      - key: DATABASE_URL
        fromDatabase:
          name: kabianga-lost-and-found-db
          property: connectionString
      - key: DB_NAME
        value: kabianga_lost_and_found
      - key: EMAIL_FROM
        value: 'Kabianga Lost & Found <no-reply@kabianga.ac.ke>'

databases:
  - name: kabianga-lost-and-found-db
    engine: postgres
    version: '15'
    plan: starter
    databaseName: kabianga_lost_and_found
    user: render
    password: render
